### ISSUE TITLE
Cannot reinsert removed document

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#139]
Because a removed document retains meta and $loki, it cannot be reinserted. During remove() those properties should be removed from the object.

**Comment by techfort** [comment]
This is fixed.

**Comment by mustafamamun** [comment]
Still having the issue. Cannot reinsert document after deleting it.
