### ISSUE TITLE
Switch to Promise based async methods

### ISSUE THREAD

**Issue by Cortys** [techfort/LokiJS#482]
Currently all async methods of the API use callbacks. I want to propose moving to a Promise based implementation.

**To clarify:**
- Most Loki methods currently are synchronous. This issue is not about changing that part of the API. Find, insert, update and remove would stay as they are.
- Only parts of the API that currently use callbacks for **singular** async events would be changed. So the API around event emitters would also remain unchanged.

**These methods / functions would be changed:**
- `Loki` & `Loki.prototype.configureOptions`: The `options` parameter of those has an `autoloadCallback` property, that would not fit a Promise based API. I'm not entirely sure what's the best way to handle this, since simply returning a Promise is not an option for the `Loki` constructor.
- `Loki.prototype.close`: Should be easy to port.
- `Loki.prototype.loadDatabase`: Should be easy to port.
- `Loki.prototype.saveDatabase`: Should be easy to port.
- `Loki.prototype.deleteDatabase`: Should be easy to port.
- `Loki`*`{Fs|LocalStorage|...}`*`Adapter.prototype.loadDatabase`: Should be easy to port.
- `Loki`*`{Fs|LocalStorage|...}`*`Adapter.prototype.saveDatabase`: Should be easy to port.
- `Loki`*`{Fs|LocalStorage|...}`*`Adapter.prototype.deleteDatabase`: Should be easy to port.
- `Loki.prototype.autosaveEnable`: Currently takes an `options` and a `callback` parameter. Since the callback is called after every autosave it is actually an event handler and should not be ported. To prevent confusion, maybe the `callback` arg should be moved into the `options` object.
- `Collection.prototype.ensureIdAsync`: While I'm not completely sure why an async version of the `ensureId` method exists (since it just calls `ensureId` and thus does not prevent lockup of the main thread), it should be easily portable as well.
- `Collection.prototype.async`: This method is only used by `Collection.prototype.ensureIdAsync`. Porting it should be easy but again I'm not really sure why it is part of the Loki API. Maybe it is better to simply remove it?

I only did a quick skim through the code so it is very possible that I missed a method...

As discussed in #474, this (depending on the specific implementation) might be a breaking change and should thus not be landed until 2.0.

**Comment by obeliskos** [comment]
Well thought out... I pretty much agree on all points.  

As for autoloadCallback, i am guessing best practice is to have separate method for storageAdapter configuration.  At this level you might configure autosave/autoload, passing in storage adapter and it could return promise or null if no init specified.  We might want to extract filesystem adapter out into its own file to avoid webpack or other environments which may not support fs module.

ensureIdAsync and collection.prototype.async could probably be removed as you said.  

I am not sure it was fully thought out to add autosaveCallback.  Unless i am forgetting something i don't think we use it and am not sure of its value to user... so we could get rid of that or refactor and repurpose if useful for other purposes.  It is possible with non-blocking io persistence adapters and (too?) low of an interval that we will overlap saves.  This might be prevented with flags in loki (or maybe internal promise?) to prevent this, or handled in storage adapters, or our setInterval could become setTimeout which begins another setTimeout when complete.  Not sure if you have any ideas there but refactoring may occur on that front as well as we rethink async.

**Comment by Cortys** [comment]
**Regarding `autoloadCallback`:**

1. To make the return values more predictable (returning a Promise if `autoload` is `true` and `null` if not might be confusing) maybe we could simply remove the autoload feature and require the user to explicitly call `loadDatabase`, which would always return a Promise. With this solution the storage adapter could still be passed to the constructor and loading would always happen in a separate call. The resulting API would IMHO still be easily usable:
  ```js
  const loki = new Loki("test", {
    adapter: Loki.persistenceAdapters.fs,
    autosave: true,
    ...
  });
  
  loki.loadDatabase({
    collectionA: { ... } // inflation options
  }).then(() => console.log("Database loaded."));
  ```
2. *(Not directly related to the Promise issue)* Another thing I noticed is that in the [autoload implementation](https://github.com/techfort/LokiJS/blob/51048324a8447a134fca44c9c79e67c71e848748/src/lokijs.js#L750) the `options` param of `configureOptions()` is directly passed to `loadDatabase()` even though the options both take are completely different. Is this intended?

Apart from those two points I agree. How should implementation be handled? Are there any plans for other changes that this issue should wait for?

**Comment by obeliskos** [comment]
Well specifying persistence settings like autosave in constructor but not knowing when to begin interval timer seems a little confusing which is why I was thinking of putting that configuration into some kind of configurePersistence() or initialize() method which would return some kind of 'ready' promise you could tap into.  If they just want want to use it in-memory they can either not bother calling initialize() or pass empty options and it will just do nothing.

Your code example looks good (I am liking the lambda and then-able syntax) but there is expectation that will perform line 2 immediately (or before an interval timer)... if not we will overwrite their database (having kicked off the autosave clockworks but not the loading).

As to you no. 2 : options passing to autoload, yea it looks like its only being used to pass down to loadJSONObject for use as nested scope for of an inline function makeLoader [here](https://github.com/techfort/LokiJS/blob/51048324a8447a134fca44c9c79e67c71e848748/src/lokijs.js#L974).  Looks like legacy inflater refactored into utility method off Loki, but since its no longer collection method they don't have access to collection options... I agree that should definitely be cleaned up for a refactor :)

**Comment by Cortys** [comment]
I see. Had not thought about the `autosave` override issue. If I understood correctly you are suggesting putting all configuration in an `initialize` method, like this:

```js
const loki = new Loki("test");

loki.initialize({
  adapter: Loki.persistenceAdapters.fs,
  autosave: true,
  inflate: { // optional inflation options
    collectionA: { ... }
  },
  ...
}).then(() => console.log("Database loaded."));
```

As you said this should solve the timing issue and I think it's also a bit cleaner since all configuration is now done at a single position and not spread across multiple method calls anymore.

**Comment by obeliskos** [comment]
Your example looks great, if you need to adapt feel free but something like that will probably be good separation.  I think a few options will be left on constructor, but anything persistence or maybe anything that kicks off async process should be moved to some kind of init.

**Comment by Cortys** [comment]
Do you have any specific options in mind that would stay on the constructor?

**Comment by obeliskos** [comment]
At the moment I can only think of the 'verbose' option which determines whether we log errors to console.  I was planning on adding some kind of 'prettyJson' option as serialization option to format but I can see that going either place.  

My thought is that some web users wont save their database, it will just be a local cache of objects received from server which they can query on.  There are even use cases where they might want to call serialize directly (maybe to clone, extract, and submit to server).  I was thinking those use cases not involving adapter at all would not need to call an initialize function.  

Still early and if you feel otherwise inspired, feel free to pursue other lines of thinking as it makes sense.

**Comment by Cortys** [comment]
I agree. If we split the options as you suggested, I think the `initialize` name is not quite fitting though. Something like `initializePersistence` would probably be better.

**Comment by Cortys** [comment]
If there is any interest, I can work on a PR for this. Just let me know.

**Comment by obeliskos** [comment]
Sure that would be great... feel free to reorg in 2.0 as much as you want.  I think the only caveats are minimal dependencies.  Out of curiosity, do you use loki in node/browser/both or other?

@techfort is unresponsive recently, hopefully when he comes back he will make you a contributor to commit whenever you want.

**Comment by Cortys** [comment]
Ok, great. I'll try to get it done during the weekend.

Personally I've been using Loki in Node for about a year now.

**Comment by obeliskos** [comment]
Hey @techfort I have seen your username pop up in activity.  Can you add Cortys to collaborators?

**Comment by Cortys** [comment]
@techfort Thanks!

I just implemented this. To make sure everybody agrees with the new API I opened a pull request instead of directly merging.

**Comment by Cortys** [comment]
Implemented and merged into the 2.0.0 branch via #497.

**Comment by kerberjg** [comment]
Hello, quick question: this seems to be merged since quite a while, yet the docs at https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html seem to be still showing callbacks instead of promises. Is this an error in the docs, or this hasn't been actually released?

**Comment by Viatorus** [comment]
Promises are used in [LokiDB](https://github.com/LokiJS-Forge/LokiDB) (official successor, not yet released).

**Comment by kerberjg** [comment]
Can LokiJS be considered deprecated then?

**Comment by Viatorus** [comment]
After LokiDBs release -> yes.

**Comment by kerberjg** [comment]
Good to know, thank you 👍

**Comment by obeliskos** [comment]
Currently LokiJS is the most stable API (as in fewer breaking changes), but soon we should be ready to offer good upgrade path to LokiDB.

**Comment by greaterking** [comment]
SWEET! Excited. Really love this lib great work!

**Comment by husayt** [comment]
There were no updates in [LokiDB](https://github.com/LokiJS-Forge/LokiDB) repo since for over 6 months now. Does it mean project is stale? I am just considering between pouchdb and Loki, and hence the question.

**Comment by greaterking** [comment]
Sadly looks like this great lib is either dead or dying :/
